gui:
  theme:
    selectedLineBgColor:
      - blue
  returnImmediately: true
stats:
  graphs:
    - caption: CPU (%)
      statPath: DerivedStats.CPUPercentage
      color: green
    - caption: Memory (%)
      statPath: DerivedStats.MemoryPercentage
      color: green
